### ISSUE TITLE
Fix issues with constructor injection and builder methods in DTOs for successful unit test compilation

### ISSUE THREAD

**Issue by klad3** [klad3/sm-sum-api#1]
The following issues were encountered during the unit test compilation:
1. **`CreateUserRequest` DTO does not have a `builder()` method:**
   - The test code is trying to use the `builder()` method to instantiate `CreateUserRequest`, but the method is missing. This is causing compilation failures when running the tests.
   
2. **`HttpClientUtil` constructor not accepting `HttpClient` argument:**
   - The `HttpClientUtil` class is being tested with a custom `HttpClient`, but its constructor does not support injecting a `HttpClient`. The constructor signature only accepts no arguments, causing errors in tests that require a mock `HttpClient`.

**Comment by bitzok** [comment]
I fixed this issue in this commit 90db456dde9c827abe08efdc731ee226e608d712
